# Generated by Django 4.0.1 on 2022-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.TextField(default=''),
        ),
    ]
