# Generated by Django 4.0.1 on 2022-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip',
        ),
        migrations.AddField(
            model_name='profile',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
